// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keys.proto

package pbkeys

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{0}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type VerifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{1}
}
func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (dst *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(dst, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

type RemoveNameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNameResponse) Reset()         { *m = RemoveNameResponse{} }
func (m *RemoveNameResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveNameResponse) ProtoMessage()    {}
func (*RemoveNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{2}
}
func (m *RemoveNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNameResponse.Unmarshal(m, b)
}
func (m *RemoveNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNameResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNameResponse.Merge(dst, src)
}
func (m *RemoveNameResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveNameResponse.Size(m)
}
func (m *RemoveNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNameResponse proto.InternalMessageInfo

type AddNameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNameResponse) Reset()         { *m = AddNameResponse{} }
func (m *AddNameResponse) String() string { return proto.CompactTextString(m) }
func (*AddNameResponse) ProtoMessage()    {}
func (*AddNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{3}
}
func (m *AddNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNameResponse.Unmarshal(m, b)
}
func (m *AddNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNameResponse.Marshal(b, m, deterministic)
}
func (dst *AddNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNameResponse.Merge(dst, src)
}
func (m *AddNameResponse) XXX_Size() int {
	return xxx_messageInfo_AddNameResponse.Size(m)
}
func (m *AddNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNameResponse proto.InternalMessageInfo

type RemoveNameRequest struct {
	Keyname              string   `protobuf:"bytes,1,opt,name=keyname,proto3" json:"keyname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNameRequest) Reset()         { *m = RemoveNameRequest{} }
func (m *RemoveNameRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNameRequest) ProtoMessage()    {}
func (*RemoveNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{4}
}
func (m *RemoveNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNameRequest.Unmarshal(m, b)
}
func (m *RemoveNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNameRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNameRequest.Merge(dst, src)
}
func (m *RemoveNameRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNameRequest.Size(m)
}
func (m *RemoveNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNameRequest proto.InternalMessageInfo

func (m *RemoveNameRequest) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

type GenRequest struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Curvetype            string   `protobuf:"bytes,2,opt,name=curvetype,proto3" json:"curvetype,omitempty"`
	Keyname              string   `protobuf:"bytes,3,opt,name=keyname,proto3" json:"keyname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenRequest) Reset()         { *m = GenRequest{} }
func (m *GenRequest) String() string { return proto.CompactTextString(m) }
func (*GenRequest) ProtoMessage()    {}
func (*GenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{5}
}
func (m *GenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenRequest.Unmarshal(m, b)
}
func (m *GenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenRequest.Marshal(b, m, deterministic)
}
func (dst *GenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenRequest.Merge(dst, src)
}
func (m *GenRequest) XXX_Size() int {
	return xxx_messageInfo_GenRequest.Size(m)
}
func (m *GenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenRequest proto.InternalMessageInfo

func (m *GenRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *GenRequest) GetCurvetype() string {
	if m != nil {
		return m.Curvetype
	}
	return ""
}

func (m *GenRequest) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

type GenResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenResponse) Reset()         { *m = GenResponse{} }
func (m *GenResponse) String() string { return proto.CompactTextString(m) }
func (*GenResponse) ProtoMessage()    {}
func (*GenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{6}
}
func (m *GenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenResponse.Unmarshal(m, b)
}
func (m *GenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenResponse.Marshal(b, m, deterministic)
}
func (dst *GenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenResponse.Merge(dst, src)
}
func (m *GenResponse) XXX_Size() int {
	return xxx_messageInfo_GenResponse.Size(m)
}
func (m *GenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenResponse proto.InternalMessageInfo

func (m *GenResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PubRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubRequest) Reset()         { *m = PubRequest{} }
func (m *PubRequest) String() string { return proto.CompactTextString(m) }
func (*PubRequest) ProtoMessage()    {}
func (*PubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{7}
}
func (m *PubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubRequest.Unmarshal(m, b)
}
func (m *PubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubRequest.Marshal(b, m, deterministic)
}
func (dst *PubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubRequest.Merge(dst, src)
}
func (m *PubRequest) XXX_Size() int {
	return xxx_messageInfo_PubRequest.Size(m)
}
func (m *PubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PubRequest proto.InternalMessageInfo

func (m *PubRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PubRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PubResponse struct {
	Pub                  []byte   `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	Curvetype            string   `protobuf:"bytes,2,opt,name=curvetype,proto3" json:"curvetype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubResponse) Reset()         { *m = PubResponse{} }
func (m *PubResponse) String() string { return proto.CompactTextString(m) }
func (*PubResponse) ProtoMessage()    {}
func (*PubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{8}
}
func (m *PubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubResponse.Unmarshal(m, b)
}
func (m *PubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubResponse.Marshal(b, m, deterministic)
}
func (dst *PubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubResponse.Merge(dst, src)
}
func (m *PubResponse) XXX_Size() int {
	return xxx_messageInfo_PubResponse.Size(m)
}
func (m *PubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PubResponse proto.InternalMessageInfo

func (m *PubResponse) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *PubResponse) GetCurvetype() string {
	if m != nil {
		return m.Curvetype
	}
	return ""
}

type ImportJSONRequest struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	JSON                 string   `protobuf:"bytes,2,opt,name=JSON,proto3" json:"JSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportJSONRequest) Reset()         { *m = ImportJSONRequest{} }
func (m *ImportJSONRequest) String() string { return proto.CompactTextString(m) }
func (*ImportJSONRequest) ProtoMessage()    {}
func (*ImportJSONRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{9}
}
func (m *ImportJSONRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportJSONRequest.Unmarshal(m, b)
}
func (m *ImportJSONRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportJSONRequest.Marshal(b, m, deterministic)
}
func (dst *ImportJSONRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportJSONRequest.Merge(dst, src)
}
func (m *ImportJSONRequest) XXX_Size() int {
	return xxx_messageInfo_ImportJSONRequest.Size(m)
}
func (m *ImportJSONRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportJSONRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportJSONRequest proto.InternalMessageInfo

func (m *ImportJSONRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *ImportJSONRequest) GetJSON() string {
	if m != nil {
		return m.JSON
	}
	return ""
}

type ImportResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportResponse) Reset()         { *m = ImportResponse{} }
func (m *ImportResponse) String() string { return proto.CompactTextString(m) }
func (*ImportResponse) ProtoMessage()    {}
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{10}
}
func (m *ImportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportResponse.Unmarshal(m, b)
}
func (m *ImportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportResponse.Marshal(b, m, deterministic)
}
func (dst *ImportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportResponse.Merge(dst, src)
}
func (m *ImportResponse) XXX_Size() int {
	return xxx_messageInfo_ImportResponse.Size(m)
}
func (m *ImportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportResponse proto.InternalMessageInfo

func (m *ImportResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ImportRequest struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Curvetype            string   `protobuf:"bytes,3,opt,name=curvetype,proto3" json:"curvetype,omitempty"`
	Keybytes             []byte   `protobuf:"bytes,4,opt,name=keybytes,proto3" json:"keybytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportRequest) Reset()         { *m = ImportRequest{} }
func (m *ImportRequest) String() string { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()    {}
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{11}
}
func (m *ImportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRequest.Unmarshal(m, b)
}
func (m *ImportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRequest.Marshal(b, m, deterministic)
}
func (dst *ImportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRequest.Merge(dst, src)
}
func (m *ImportRequest) XXX_Size() int {
	return xxx_messageInfo_ImportRequest.Size(m)
}
func (m *ImportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRequest proto.InternalMessageInfo

func (m *ImportRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *ImportRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImportRequest) GetCurvetype() string {
	if m != nil {
		return m.Curvetype
	}
	return ""
}

func (m *ImportRequest) GetKeybytes() []byte {
	if m != nil {
		return m.Keybytes
	}
	return nil
}

type ExportRequest struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportRequest) Reset()         { *m = ExportRequest{} }
func (m *ExportRequest) String() string { return proto.CompactTextString(m) }
func (*ExportRequest) ProtoMessage()    {}
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{12}
}
func (m *ExportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportRequest.Unmarshal(m, b)
}
func (m *ExportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportRequest.Marshal(b, m, deterministic)
}
func (dst *ExportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportRequest.Merge(dst, src)
}
func (m *ExportRequest) XXX_Size() int {
	return xxx_messageInfo_ExportRequest.Size(m)
}
func (m *ExportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExportRequest proto.InternalMessageInfo

func (m *ExportRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *ExportRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExportRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ExportResponse struct {
	Export               string   `protobuf:"bytes,1,opt,name=export,proto3" json:"export,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportResponse) Reset()         { *m = ExportResponse{} }
func (m *ExportResponse) String() string { return proto.CompactTextString(m) }
func (*ExportResponse) ProtoMessage()    {}
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{13}
}
func (m *ExportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportResponse.Unmarshal(m, b)
}
func (m *ExportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportResponse.Marshal(b, m, deterministic)
}
func (dst *ExportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportResponse.Merge(dst, src)
}
func (m *ExportResponse) XXX_Size() int {
	return xxx_messageInfo_ExportResponse.Size(m)
}
func (m *ExportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExportResponse proto.InternalMessageInfo

func (m *ExportResponse) GetExport() string {
	if m != nil {
		return m.Export
	}
	return ""
}

type SignRequest struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Message              []byte   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()    {}
func (*SignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{14}
}
func (m *SignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRequest.Unmarshal(m, b)
}
func (m *SignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRequest.Marshal(b, m, deterministic)
}
func (dst *SignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRequest.Merge(dst, src)
}
func (m *SignRequest) XXX_Size() int {
	return xxx_messageInfo_SignRequest.Size(m)
}
func (m *SignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRequest proto.InternalMessageInfo

func (m *SignRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *SignRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SignRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type SignResponse struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Curvetype            string   `protobuf:"bytes,2,opt,name=curvetype,proto3" json:"curvetype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()    {}
func (*SignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{15}
}
func (m *SignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResponse.Unmarshal(m, b)
}
func (m *SignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResponse.Marshal(b, m, deterministic)
}
func (dst *SignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResponse.Merge(dst, src)
}
func (m *SignResponse) XXX_Size() int {
	return xxx_messageInfo_SignResponse.Size(m)
}
func (m *SignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignResponse proto.InternalMessageInfo

func (m *SignResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignResponse) GetCurvetype() string {
	if m != nil {
		return m.Curvetype
	}
	return ""
}

type VerifyRequest struct {
	Curvetype            string   `protobuf:"bytes,1,opt,name=curvetype,proto3" json:"curvetype,omitempty"`
	Pub                  []byte   `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	Message              []byte   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{16}
}
func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(dst, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetCurvetype() string {
	if m != nil {
		return m.Curvetype
	}
	return ""
}

func (m *VerifyRequest) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *VerifyRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *VerifyRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type HashRequest struct {
	Hashtype             string   `protobuf:"bytes,1,opt,name=hashtype,proto3" json:"hashtype,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashRequest) Reset()         { *m = HashRequest{} }
func (m *HashRequest) String() string { return proto.CompactTextString(m) }
func (*HashRequest) ProtoMessage()    {}
func (*HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{17}
}
func (m *HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashRequest.Unmarshal(m, b)
}
func (m *HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashRequest.Marshal(b, m, deterministic)
}
func (dst *HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRequest.Merge(dst, src)
}
func (m *HashRequest) XXX_Size() int {
	return xxx_messageInfo_HashRequest.Size(m)
}
func (m *HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashRequest proto.InternalMessageInfo

func (m *HashRequest) GetHashtype() string {
	if m != nil {
		return m.Hashtype
	}
	return ""
}

func (m *HashRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type HashResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashResponse) Reset()         { *m = HashResponse{} }
func (m *HashResponse) String() string { return proto.CompactTextString(m) }
func (*HashResponse) ProtoMessage()    {}
func (*HashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{18}
}
func (m *HashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashResponse.Unmarshal(m, b)
}
func (m *HashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashResponse.Marshal(b, m, deterministic)
}
func (dst *HashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashResponse.Merge(dst, src)
}
func (m *HashResponse) XXX_Size() int {
	return xxx_messageInfo_HashResponse.Size(m)
}
func (m *HashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashResponse proto.InternalMessageInfo

func (m *HashResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Key struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Keyname              string   `protobuf:"bytes,2,opt,name=keyname,proto3" json:"keyname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{19}
}
func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (dst *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(dst, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Key) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

type ListResponse struct {
	Key                  []*Key   `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{20}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetKey() []*Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type AddNameRequest struct {
	Keyname              string   `protobuf:"bytes,1,opt,name=keyname,proto3" json:"keyname,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNameRequest) Reset()         { *m = AddNameRequest{} }
func (m *AddNameRequest) String() string { return proto.CompactTextString(m) }
func (*AddNameRequest) ProtoMessage()    {}
func (*AddNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_b55d59adec320799, []int{21}
}
func (m *AddNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNameRequest.Unmarshal(m, b)
}
func (m *AddNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNameRequest.Marshal(b, m, deterministic)
}
func (dst *AddNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNameRequest.Merge(dst, src)
}
func (m *AddNameRequest) XXX_Size() int {
	return xxx_messageInfo_AddNameRequest.Size(m)
}
func (m *AddNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNameRequest proto.InternalMessageInfo

func (m *AddNameRequest) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

func (m *AddNameRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "pbkeys.ListRequest")
	proto.RegisterType((*VerifyResponse)(nil), "pbkeys.VerifyResponse")
	proto.RegisterType((*RemoveNameResponse)(nil), "pbkeys.RemoveNameResponse")
	proto.RegisterType((*AddNameResponse)(nil), "pbkeys.AddNameResponse")
	proto.RegisterType((*RemoveNameRequest)(nil), "pbkeys.RemoveNameRequest")
	proto.RegisterType((*GenRequest)(nil), "pbkeys.GenRequest")
	proto.RegisterType((*GenResponse)(nil), "pbkeys.GenResponse")
	proto.RegisterType((*PubRequest)(nil), "pbkeys.PubRequest")
	proto.RegisterType((*PubResponse)(nil), "pbkeys.PubResponse")
	proto.RegisterType((*ImportJSONRequest)(nil), "pbkeys.ImportJSONRequest")
	proto.RegisterType((*ImportResponse)(nil), "pbkeys.ImportResponse")
	proto.RegisterType((*ImportRequest)(nil), "pbkeys.ImportRequest")
	proto.RegisterType((*ExportRequest)(nil), "pbkeys.ExportRequest")
	proto.RegisterType((*ExportResponse)(nil), "pbkeys.ExportResponse")
	proto.RegisterType((*SignRequest)(nil), "pbkeys.SignRequest")
	proto.RegisterType((*SignResponse)(nil), "pbkeys.SignResponse")
	proto.RegisterType((*VerifyRequest)(nil), "pbkeys.VerifyRequest")
	proto.RegisterType((*HashRequest)(nil), "pbkeys.HashRequest")
	proto.RegisterType((*HashResponse)(nil), "pbkeys.HashResponse")
	proto.RegisterType((*Key)(nil), "pbkeys.Key")
	proto.RegisterType((*ListResponse)(nil), "pbkeys.ListResponse")
	proto.RegisterType((*AddNameRequest)(nil), "pbkeys.AddNameRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeysClient is the client API for Keys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeysClient interface {
	GenerateKey(ctx context.Context, in *GenRequest, opts ...grpc.CallOption) (*GenResponse, error)
	PublicKey(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResponse, error)
	ImportJSON(ctx context.Context, in *ImportJSONRequest, opts ...grpc.CallOption) (*ImportResponse, error)
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	RemoveName(ctx context.Context, in *RemoveNameRequest, opts ...grpc.CallOption) (*RemoveNameResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	AddName(ctx context.Context, in *AddNameRequest, opts ...grpc.CallOption) (*AddNameResponse, error)
}

type keysClient struct {
	cc *grpc.ClientConn
}

func NewKeysClient(cc *grpc.ClientConn) KeysClient {
	return &keysClient{cc}
}

func (c *keysClient) GenerateKey(ctx context.Context, in *GenRequest, opts ...grpc.CallOption) (*GenResponse, error) {
	out := new(GenResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/GenerateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) PublicKey(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error) {
	out := new(PubResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/PublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResponse, error) {
	out := new(ImportResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/Import", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) ImportJSON(ctx context.Context, in *ImportJSONRequest, opts ...grpc.CallOption) (*ImportResponse, error) {
	out := new(ImportResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/ImportJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/Export", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/Hash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) RemoveName(ctx context.Context, in *RemoveNameRequest, opts ...grpc.CallOption) (*RemoveNameResponse, error) {
	out := new(RemoveNameResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/RemoveName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) AddName(ctx context.Context, in *AddNameRequest, opts ...grpc.CallOption) (*AddNameResponse, error) {
	out := new(AddNameResponse)
	err := c.cc.Invoke(ctx, "/pbkeys.Keys/AddName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeysServer is the server API for Keys service.
type KeysServer interface {
	GenerateKey(context.Context, *GenRequest) (*GenResponse, error)
	PublicKey(context.Context, *PubRequest) (*PubResponse, error)
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	Import(context.Context, *ImportRequest) (*ImportResponse, error)
	ImportJSON(context.Context, *ImportJSONRequest) (*ImportResponse, error)
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	Hash(context.Context, *HashRequest) (*HashResponse, error)
	RemoveName(context.Context, *RemoveNameRequest) (*RemoveNameResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	AddName(context.Context, *AddNameRequest) (*AddNameResponse, error)
}

func RegisterKeysServer(s *grpc.Server, srv KeysServer) {
	s.RegisterService(&_Keys_serviceDesc, srv)
}

func _Keys_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/GenerateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).GenerateKey(ctx, req.(*GenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_PublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).PublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/PublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).PublicKey(ctx, req.(*PubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Import_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Import(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Import",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Import(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_ImportJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).ImportJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/ImportJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).ImportJSON(ctx, req.(*ImportJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Export",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_RemoveName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).RemoveName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/RemoveName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).RemoveName(ctx, req.(*RemoveNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_AddName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).AddName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/AddName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).AddName(ctx, req.(*AddNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Keys_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbkeys.Keys",
	HandlerType: (*KeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKey",
			Handler:    _Keys_GenerateKey_Handler,
		},
		{
			MethodName: "PublicKey",
			Handler:    _Keys_PublicKey_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _Keys_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Keys_Verify_Handler,
		},
		{
			MethodName: "Import",
			Handler:    _Keys_Import_Handler,
		},
		{
			MethodName: "ImportJSON",
			Handler:    _Keys_ImportJSON_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _Keys_Export_Handler,
		},
		{
			MethodName: "Hash",
			Handler:    _Keys_Hash_Handler,
		},
		{
			MethodName: "RemoveName",
			Handler:    _Keys_RemoveName_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Keys_List_Handler,
		},
		{
			MethodName: "AddName",
			Handler:    _Keys_AddName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keys.proto",
}

func init() { proto.RegisterFile("keys.proto", fileDescriptor_keys_b55d59adec320799) }

var fileDescriptor_keys_b55d59adec320799 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x6f, 0xd3, 0x4c,
	0x10, 0x55, 0x62, 0x2b, 0x6d, 0x9e, 0x93, 0x7c, 0xed, 0x7e, 0xa5, 0x04, 0xab, 0xa0, 0x6a, 0x2f,
	0x54, 0x48, 0xad, 0xd4, 0x82, 0xa8, 0xa8, 0x84, 0x10, 0x2a, 0xa8, 0xd0, 0xa2, 0x52, 0xa5, 0x12,
	0x37, 0x0e, 0x4e, 0x33, 0x34, 0x51, 0x48, 0x62, 0xbc, 0x76, 0xc1, 0x07, 0xfe, 0x71, 0x4e, 0xc8,
	0xde, 0xdd, 0xec, 0xae, 0xfb, 0x2b, 0x12, 0xb7, 0x9d, 0xd9, 0x99, 0x79, 0x33, 0xe3, 0xe7, 0xb7,
	0xc0, 0x98, 0x72, 0xb1, 0x13, 0x27, 0xb3, 0x74, 0xc6, 0x1a, 0x71, 0xbf, 0xb0, 0x78, 0x1b, 0xc1,
	0xa7, 0x91, 0x48, 0x7b, 0xf4, 0x23, 0x23, 0x91, 0xf2, 0x15, 0x74, 0xbe, 0x50, 0x32, 0xfa, 0x96,
	0xf7, 0x48, 0xc4, 0xb3, 0xa9, 0x20, 0xbe, 0x06, 0xd6, 0xa3, 0xc9, 0xec, 0x8a, 0x4e, 0xa3, 0x09,
	0xcd, 0xbd, 0xab, 0xf8, 0xef, 0xed, 0x60, 0xe0, 0xb8, 0xb6, 0xb1, 0x6a, 0x07, 0x96, 0xf5, 0x58,
	0x17, 0x4b, 0x63, 0xca, 0xa7, 0xd1, 0x84, 0xba, 0xb5, 0xcd, 0xda, 0x56, 0xb3, 0xa7, 0x4d, 0x3e,
	0x00, 0x8e, 0x68, 0xaa, 0xe3, 0x9e, 0x00, 0x71, 0x24, 0x44, 0x3c, 0x4c, 0x22, 0xa1, 0x43, 0x2d,
	0x0f, 0xdb, 0x40, 0xf3, 0x22, 0x4b, 0xae, 0x28, 0xcd, 0x63, 0xea, 0xd6, 0xcb, 0x6b, 0xe3, 0xb0,
	0x51, 0x3c, 0x17, 0xe5, 0x29, 0x82, 0x12, 0x45, 0xf6, 0x58, 0x04, 0x46, 0x83, 0x41, 0x42, 0x42,
	0xe8, 0x76, 0x94, 0xc9, 0x0f, 0x80, 0xb3, 0xac, 0x6f, 0xb5, 0x7d, 0x73, 0x1c, 0x63, 0xf0, 0x4b,
	0x1c, 0xd9, 0x43, 0x79, 0xe6, 0xaf, 0x11, 0x94, 0xb9, 0x0a, 0x64, 0x05, 0x5e, 0x9c, 0xf5, 0xcb,
	0xc4, 0x56, 0xaf, 0x38, 0xde, 0xdd, 0x3d, 0x3f, 0xc2, 0xea, 0xc7, 0x49, 0x3c, 0x4b, 0xd2, 0xe3,
	0xf3, 0xcf, 0xa7, 0x8b, 0x2e, 0x84, 0xc1, 0x2f, 0xc2, 0x75, 0x1f, 0xc5, 0x99, 0x3f, 0x43, 0x47,
	0x16, 0x5a, 0x60, 0xde, 0xdf, 0x68, 0xeb, 0xd8, 0x85, 0x01, 0xab, 0x83, 0xbb, 0x73, 0x79, 0xd5,
	0xaf, 0x12, 0x62, 0x79, 0x4c, 0x79, 0x3f, 0x4f, 0x49, 0x74, 0xfd, 0x72, 0x19, 0x73, 0x9b, 0x7f,
	0x45, 0xfb, 0xfd, 0xaf, 0x7f, 0x85, 0xb7, 0xa6, 0xf3, 0xdc, 0xe9, 0xb6, 0xd0, 0xd1, 0xe5, 0xd5,
	0x26, 0xd6, 0xd1, 0xa0, 0xd2, 0xa3, 0x6a, 0x2b, 0x8b, 0x67, 0x08, 0xce, 0x47, 0x97, 0x0b, 0xf3,
	0xd0, 0x82, 0xac, 0xdf, 0x4c, 0x0c, 0xcf, 0x6d, 0x70, 0x42, 0x42, 0x44, 0x97, 0xa4, 0x16, 0xa0,
	0x4d, 0x7e, 0x8c, 0x96, 0x84, 0x55, 0xed, 0x6d, 0xa0, 0x29, 0x46, 0x97, 0xd3, 0x28, 0xcd, 0x12,
	0x52, 0xcc, 0x31, 0x8e, 0x7b, 0xf8, 0xf3, 0x13, 0x6d, 0xfd, 0xcf, 0xca, 0x21, 0x9c, 0xf0, 0x5a,
	0xf5, 0xb3, 0x28, 0x7a, 0xd6, 0x0d, 0x3d, 0xad, 0x36, 0x3d, 0xa7, 0x4d, 0xb7, 0x2d, 0xbf, 0xd2,
	0x16, 0x3f, 0x44, 0xf0, 0x21, 0x12, 0x43, 0x0d, 0x1b, 0x62, 0x79, 0x18, 0x89, 0xa1, 0x85, 0x3a,
	0xb7, 0x6d, 0x88, 0xba, 0xbb, 0x09, 0x8e, 0x96, 0x2c, 0xa2, 0x36, 0xc1, 0xe0, 0x17, 0x59, 0xaa,
	0x42, 0x79, 0xe6, 0xaf, 0xe0, 0x9d, 0x50, 0x7e, 0xc7, 0x5f, 0x69, 0x09, 0x40, 0xdd, 0x15, 0x80,
	0x6d, 0xb4, 0xa4, 0xbe, 0xa9, 0xf2, 0x8f, 0xe1, 0x8d, 0x29, 0xef, 0xd6, 0x36, 0xbd, 0xad, 0x60,
	0x2f, 0xd8, 0x91, 0x2a, 0xb8, 0x73, 0x42, 0x79, 0xaf, 0xf0, 0xf3, 0x77, 0xe8, 0xcc, 0x75, 0xed,
	0x1e, 0x05, 0xbb, 0x9d, 0x0b, 0x7b, 0x7f, 0x7c, 0xf8, 0x27, 0x94, 0x0b, 0xf6, 0xb2, 0x94, 0x1f,
	0x4a, 0xa2, 0x94, 0x8a, 0x01, 0x98, 0xc6, 0x33, 0xca, 0x17, 0xfe, 0xef, 0xf8, 0x54, 0x97, 0x2f,
	0xd0, 0x3c, 0xcb, 0xfa, 0xdf, 0x47, 0x17, 0x4e, 0x96, 0x11, 0x28, 0x93, 0x65, 0x0b, 0xcf, 0x2e,
	0xfc, 0x82, 0x54, 0x6c, 0x7e, 0x69, 0x31, 0x3b, 0x5c, 0x73, 0x9d, 0x2a, 0x65, 0x1f, 0x0d, 0xc9,
	0x1d, 0xf6, 0x40, 0xdf, 0x3b, 0x5c, 0x0a, 0xd7, 0xab, 0x6e, 0x93, 0x28, 0xf5, 0xc3, 0x24, 0x3a,
	0x7a, 0x62, 0x12, 0x2b, 0x92, 0xf4, 0x06, 0x30, 0x6a, 0xc7, 0x1e, 0xb9, 0x51, 0x96, 0x02, 0xde,
	0x5a, 0x60, 0x1f, 0x0d, 0xf9, 0x6f, 0x1b, 0x64, 0x47, 0x4a, 0x4c, 0x62, 0x45, 0x02, 0x76, 0xe1,
	0x17, 0x4c, 0x33, 0xeb, 0xb1, 0xc8, 0x6b, 0xd6, 0xe3, 0x90, 0xf1, 0x10, 0x30, 0x6f, 0x9a, 0x69,
	0xf6, 0xda, 0x3b, 0x17, 0x86, 0x37, 0x5d, 0x19, 0xdc, 0x82, 0x82, 0x06, 0xd7, 0x7a, 0x70, 0x0d,
	0xae, 0xc3, 0xd2, 0x03, 0x2c, 0x29, 0x1a, 0xb2, 0xf9, 0x34, 0x2e, 0x2f, 0xc3, 0x87, 0xd7, 0xfc,
	0x32, 0xb7, 0xdf, 0x28, 0x1f, 0xf8, 0xe7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xfa, 0x1e,
	0x64, 0xee, 0x07, 0x00, 0x00,
}
